class CodeGeneratorService:

    def __init__(
        self,
        chat_service=None,
    ):

        self.chat_service = chat_service

    def generate_code(
        self,
        step=None,
        execution_state=None,
    ):

        step = (
            step
            if isinstance(step, dict)
            else {}
        )

        execution_state = (
            execution_state
            if isinstance(execution_state, dict)
            else {}
        )

        title = str(
            step.get("title") or ""
        ).lower()

        target_file = str(
            step.get("target_file") or ""
        )

        original_goal = str(
            execution_state.get(
                "original_user_text"
            )
            or ""
        )

        if "calculator" in original_goal.lower():

            return {
                "ok": True,
                "target_file": target_file,
                "code": '''
def add(a, b):
    return a + b


def subtract(a, b):
    return a - b


def multiply(a, b):
    return a * b


def divide(a, b):

    if b == 0:
        raise ValueError(
            "Cannot divide by zero."
        )

    return a / b


if __name__ == "__main__":

    print("Calculator App")
    print("2 + 3 =", add(2, 3))
    print("10 - 4 =", subtract(10, 4))
    print("6 * 7 =", multiply(6, 7))
    print("8 / 2 =", divide(8, 2))
'''.strip()
                + "\n",
            }

        return {
            "ok": True,
            "target_file": target_file,
            "code": '''
print("Generated by Nova.")
'''.strip()
            + "\n",
        }